numpy prac

In [5]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5])


In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr[0]

np.int64(1)

In [9]:
arr[-1]

np.int64(5)

In [10]:
arr[0:2]

array([1, 2])

In [11]:
type(arr)

numpy.ndarray

In [12]:
matrix_4_5 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])

In [13]:
matrix_4_5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
matrix_4_5[0][3]

np.int64(4)

In [15]:
arr = np.zeros(10)

In [16]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.ones(10)

In [18]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.arange(2,15)

In [21]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr = np.arange(2,15,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [23]:
def arrayinfo(a):
  print(a)
  print("data type variable: ", type(a))
  print("shape of variable: ", a.shape)
  print("number of dimensions: ", a.ndim)
  print("size of variable: ", a.size)
  print("memory size of each element: ", a.itemsize)


In [24]:
arrayinfo(matrix_4_5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
data type variable:  <class 'numpy.ndarray'>
shape of variable:  (4, 5)
number of dimensions:  2
size of variable:  20
memory size of each element:  8


In [25]:
arr_lnsp = np.linspace(2,10,8)
arr_lnsp

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [26]:
arr_lnsp = np.linspace(1,5,20)
arr_lnsp

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

arithmetic operations

In [27]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[10,11,12]])

arr = arr1 + arr2
arr

array([[ 5,  7,  9],
       [17, 19, 21]])

In [28]:
arr = arr1 - arr2
arr

array([[-3, -3, -3],
       [-3, -3, -3]])

In [29]:
arr = arr1 * arr2
arr

array([[  4,  10,  18],
       [ 70,  88, 108]])

In [30]:
arr = arr1 / arr2
arr

array([[0.25      , 0.4       , 0.5       ],
       [0.7       , 0.72727273, 0.75      ]])

In [31]:
arr = arr1 // arr2
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
arr = arr2 // arr1
arr

array([[4, 2, 2],
       [1, 1, 1]])

statistical operations

In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [34]:
np.mean(arr)

np.float64(3.0)

In [35]:
np.max(arr)

np.int64(5)

In [36]:
np.min(arr)

np.int64(1)

In [37]:
np.std(arr)

np.float64(1.4142135623730951)

In [38]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [39]:
arr 

array([1, 2, 3, 4, 5])

In [40]:
arr.T

array([1, 2, 3, 4, 5])

In [41]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [42]:
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

copy & view

In [43]:
a = np.array([1,2,3,4,5])

b = a.view()

b[0] = 10

print(a)

#original array is also changed when we use view() method

[10  2  3  4  5]


In [44]:
a = np.array([1,2,3,4,5])

b = a.copy()

b[0] = 10

print(a)

#original array is not changed when we use copy() method 

[1 2 3 4 5]


sorting

In [45]:
arr = np.array([30,10,20])
arr.sort()
arr

array([10, 20, 30])

In [46]:
np.argsort(arr)


array([0, 1, 2])

In [47]:
arr = np.array([30,10,20])
np.sort(arr)


array([10, 20, 30])

In [48]:
np.argsort(arr)

array([1, 2, 0])

stacking

In [49]:
arr1 = np.array([[1, 2],[3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [50]:
arr2 = np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [51]:
array_hstack = np.hstack((arr1, arr2))
array_hstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
array_vstack = np.vstack((arr1, arr2))
array_vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
array_col = np.column_stack((arr1, arr2))
array_col

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
array_col.flatten()

array([1, 2, 5, 6, 3, 4, 7, 8])

In [55]:
array_col.flatten(order = "f")

array([1, 3, 2, 4, 5, 7, 6, 8])

random numbers

In [56]:
# will geneare one rando element
a = np.random.randint(0,100)
a

71

In [57]:

a = np.random.randint(0,1000,(3,5))
a

array([[826, 396,  78, 734, 226],
       [468, 253,  98, 338, 294],
       [398, 668, 904, 316, 668]], dtype=int32)

In [58]:
#use seed() method to generate same random numbers
np.random.seed(50)
a = np.random.randint(0,100,(2,3))
a

array([[48, 96, 11],
       [33, 94,  4]], dtype=int32)

conversion

In [59]:
a = np.array([1,2.3,5,7,8,9])
a

array([1. , 2.3, 5. , 7. , 8. , 9. ])

In [60]:
type(a)

numpy.ndarray

In [61]:
a.dtype

dtype('float64')

In [62]:
a

array([1. , 2.3, 5. , 7. , 8. , 9. ])

In [63]:
b = a.astype(int)

In [64]:
b

array([1, 2, 5, 7, 8, 9])