In [2]:
import seaborn as sns


In [3]:
df_mpg = sns.load_dataset('mpg')

In [4]:
df_mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [5]:
df_mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [6]:
df_mpg.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10


In [7]:
df_mpg.shape

(398, 9)

In [8]:
df_mpg.describe(include = 'all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN


In [9]:
df_mpg['mpg'].unique()

array([18. , 15. , 16. , 17. , 14. , 24. , 22. , 21. , 27. , 26. , 25. ,
       10. , 11. ,  9. , 28. , 19. , 12. , 13. , 23. , 30. , 31. , 35. ,
       20. , 29. , 32. , 33. , 17.5, 15.5, 14.5, 22.5, 24.5, 18.5, 29.5,
       26.5, 16.5, 31.5, 36. , 25.5, 33.5, 20.5, 30.5, 21.5, 43.1, 36.1,
       32.8, 39.4, 19.9, 19.4, 20.2, 19.2, 25.1, 20.6, 20.8, 18.6, 18.1,
       17.7, 27.5, 27.2, 30.9, 21.1, 23.2, 23.8, 23.9, 20.3, 21.6, 16.2,
       19.8, 22.3, 17.6, 18.2, 16.9, 31.9, 34.1, 35.7, 27.4, 25.4, 34.2,
       34.5, 31.8, 37.3, 28.4, 28.8, 26.8, 41.5, 38.1, 32.1, 37.2, 26.4,
       24.3, 19.1, 34.3, 29.8, 31.3, 37. , 32.2, 46.6, 27.9, 40.8, 44.3,
       43.4, 36.4, 44.6, 40.9, 33.8, 32.7, 23.7, 23.6, 32.4, 26.6, 25.8,
       23.5, 39.1, 39. , 35.1, 32.3, 37.7, 34.7, 34.4, 29.9, 33.7, 32.9,
       31.6, 28.1, 30.7, 24.2, 22.4, 34. , 38. , 44. ])

In [10]:
df_mpg['mpg_int'] = df_mpg['mpg'].astype(int)    #int use less memory than float

#It converts the mpg column from a float data type to an integer data type by removing the decimal part.

In [11]:
df_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,mpg_int
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,18
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,15
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,18
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,16
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,17
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,27
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,44
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,32
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,28


-> Finding the null values

    -> isnull()
    
    -> isnull().sum()
    
    -> isnull().any()
    
    -> isnull().sum().sum()
    
    -> isnull().any().sum()


isna().sum()

In [12]:
df_new = df_mpg.isnull()

In [13]:
df_new

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,mpg_int
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
393,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False


In [14]:
df_new = df_mpg.isnull().sum()
df_new

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
mpg_int         0
dtype: int64

In [15]:
df_new.isnull().any()

np.False_

In [16]:
df_new = df_mpg.isna().sum()

In [17]:
df_new

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
mpg_int         0
dtype: int64

In [18]:
df_mpg['cylinders'].isnull().sum()


np.int64(0)

In [19]:
df_mpg[['cylinders','horsepower']].isnull().sum()

cylinders     0
horsepower    6
dtype: int64

How to fill values 

    -> forwardfill => sequential repeated values
    
    -> backwardfill => sequential repeated values
    
    -> fillna => if we know what to fill
    
    -> replace => replacing the null values wi=th someother value
    
    -> mean => replacing with mean if any extreme values then use median
    
    -> median => filling null value with middle value
    
    -> mode => using relation formula r most repeated one
    
    -> random => In set of values choosing one value
    
    -> imputer methods> sklearn 
    
    -> min -> minimum 
    
    -> max -> maximum value in the set of data

In [20]:
import pandas as pd
data = {
    'A': [1, None, None, 4, 5],
    'B': [None, 2, None, 4, None]
}
df = pd.DataFrame(data)

In [21]:
df

,A,B
0,1.0,NaN
1,NaN,2.0
2,NaN,NaN
3,4.0,4.0
4,5.0,NaN


In [22]:
df_ffill = df.ffill()

In [23]:
df_ffill

,A,B
0,1.0,NaN
1,1.0,2.0
2,1.0,2.0
3,4.0,4.0
4,5.0,4.0


In [24]:
df_bfill = df.bfill()

In [25]:
df_bfill

,A,B
0,1.0,2.0
1,4.0,2.0
2,4.0,4.0
3,4.0,4.0
4,5.0,NaN


In [26]:
# Fill null values with a specific value (e.g., 0)
df_fillna_with_spec_num = df.fillna(0)
df_fillna_with_spec_num

,A,B
0,1.0,0.0
1,0.0,2.0
2,0.0,0.0
3,4.0,4.0
4,5.0,0.0


In [27]:
# Fill null values with the mean of the column
mean_value = df['A'].mean()
print("Mean value of column A:", mean_value)
df_mean_filled = df['A'].fillna(mean_value)
df_mean_filled

Mean value of column A: 3.3333333333333335


0    1.000000
1    3.333333
2    3.333333
3    4.000000
4    5.000000
Name: A, dtype: float64

In [28]:
# Fill null values with the median of the column
median_value = df['A'].median()
print("Median value of column A:", median_value)
df_median_filled = df['A'].fillna(median_value)
df_median_filled

Median value of column A: 4.0


0    1.0
1    4.0
2    4.0
3    4.0
4    5.0
Name: A, dtype: float64

In [29]:
# Fill null values with the mode of the column
mode_value = df['A'].mode()[0]
print("Mode value of column A:", mode_value)
df_mode_filled = df['A'].fillna(mode_value)
df_mode_filled

Mode value of column A: 1.0


0    1.0
1    1.0
2    1.0
3    4.0
4    5.0
Name: A, dtype: float64

In [30]:
# Fill null values in column 'A' with its minimum value
min_value = df['A'].min()
df_min_filled = df['A'].fillna(min_value)
df_min_filled



0    1.0
1    1.0
2    1.0
3    4.0
4    5.0
Name: A, dtype: float64

In [31]:
# Fill null values in column 'A' with its maximum value
max_value = df['A'].max()
df_max_filled = df['A'].fillna(max_value)
df_max_filled

0    1.0
1    5.0
2    5.0
3    4.0
4    5.0
Name: A, dtype: float64

Scikit-learn provides several imputer methods for handling missing values:

SimpleImputer: Fills missing values with a specified strategy (mean, median, most frequent, constant).

KNNImputer: Fills missing values using the k-nearest neighbors algorithm.

IterativeImputer: Fills missing values using multivariate regression (estimates each feature as a function of others).

MissingIndicator: Creates a boolean indicator for missing values (used for feature engineering).

In [32]:
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.experimental import enable_iterative_imputer

imputer = SimpleImputer(strategy='mean')
df_imputed = imputer.fit_transform(df)
df_imputed

array([[1.        , 3.        ],
       [3.33333333, 2.        ],
       [3.33333333, 3.        ],
       [4.        , 4.        ],
       [5.        , 3.        ]])

In [33]:
knn_imputer = KNNImputer(n_neighbors=2)
df_knn_imputed = knn_imputer.fit_transform(df)
df_knn_imputed

array([[1.        , 4.        ],
       [4.        , 2.        ],
       [3.33333333, 3.        ],
       [4.        , 4.        ],
       [5.        , 4.        ]])

In [34]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

iter_imputer = IterativeImputer()

df_iter_imputed = iter_imputer.fit_transform(df)

df_iter_imputed

array([[ 1.        , -4.98644966],
       [ 3.33232868,  2.        ],
       [ 3.33308217,  2.00225806],
       [ 4.        ,  4.        ],
       [ 5.        ,  6.99548189]])

In [35]:
df = sns.load_dataset('mpg')

In [36]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino


In [37]:
df = df.sort_values(by = 'mpg')

In [38]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
...,...,...,...,...,...,...,...,...,...
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl


In [39]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis


In [40]:
df_reset = df.reset_index(drop=True)

In [41]:
df_reset.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
1,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
2,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
3,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
4,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis


titanic data set


In [42]:
import pandas as pd
import numpy as np
import seaborn as sns

In [43]:

titanic = sns.load_dataset('titanic')

In [44]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [45]:
titanic['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [46]:
titanic[0:10:2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False


In [47]:
for rec in df.iterrows():
    print(rec)
    print("====================")

(28, mpg                  9.0
cylinders              8
displacement       304.0
horsepower         193.0
weight              4732
acceleration        18.5
model_year            70
origin               usa
name            hi 1200d
Name: 28, dtype: object)
(25, mpg                  10.0
cylinders               8
displacement        360.0
horsepower          215.0
weight               4615
acceleration         14.0
model_year             70
origin                usa
name            ford f250
Name: 25, dtype: object)
(26, mpg                  10.0
cylinders               8
displacement        307.0
horsepower          200.0
weight               4376
acceleration         15.0
model_year             70
origin                usa
name            chevy c20
Name: 26, dtype: object)
(103, mpg                         11.0
cylinders                      8
displacement               400.0
horsepower                 150.0
weight                      4997
acceleration                14.0
model_year   

creating series

In [48]:
panda_series = pd.Series()

In [49]:
type(panda_series)

pandas.core.series.Series

In [50]:
panda_series


Series([], dtype: object)

In [51]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])  
ser1 = ser1.astype(int)
ser1                                 

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [52]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])   
ser2 = ser2.astype(int)     
ser2                           

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [53]:
ser = ser1 + ser2

In [54]:
ser

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [55]:
import pandas as pd
import numpy as np

In [56]:
from numpy.random import randn
np.random.seed(101)

In [63]:
df = pd.DataFrame(randn(5,4),index='A,B,C,D,E'.split(','),columns='W X Y Z'.split())

In [58]:
df

,W,X,Y,Z
A,2.706850,0.628133,0.907969,0.503826
B,0.651118,-0.319318,-0.848077,0.605965
C,-2.018168,0.740122,0.528813,-0.589001
D,0.188695,-0.758872,-0.933237,0.955057
E,0.190794,1.978757,2.605967,0.683509


In [59]:
df = pd.DataFrame(randn(1000,4),columns='col1 col2 col3 col4'.split())

In [60]:
df.shape

(1000, 4)

In [71]:
type(df["W"])

pandas.core.series.Series

In [72]:
df['new'] = df['W'] + df['Y']

In [73]:
df

,W,X,Y,Z,new
A,-1.719705,-2.034005,-0.078706,-0.564540,-1.798411
B,1.010888,-1.168972,1.950265,1.303639,2.961153
C,0.535172,0.031398,0.139456,-0.176122,0.674628
D,0.149926,-0.149309,-0.129002,-0.332997,0.020924
E,-0.766784,0.668865,-0.129419,-0.181624,-0.896203


In [74]:
df.drop('new',axis=1)

,W,X,Y,Z
A,-1.719705,-2.034005,-0.078706,-0.564540
B,1.010888,-1.168972,1.950265,1.303639
C,0.535172,0.031398,0.139456,-0.176122
D,0.149926,-0.149309,-0.129002,-0.332997
E,-0.766784,0.668865,-0.129419,-0.181624


In [75]:
df.drop('new',axis=1,inplace=True)

In [76]:
df

,W,X,Y,Z
A,-1.719705,-2.034005,-0.078706,-0.564540
B,1.010888,-1.168972,1.950265,1.303639
C,0.535172,0.031398,0.139456,-0.176122
D,0.149926,-0.149309,-0.129002,-0.332997
E,-0.766784,0.668865,-0.129419,-0.181624


In [ ]:
#DataFrame Multi-indexing (hierarchical index)
data_multi = {'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]}
df_multi = pd.DataFrame(data_multi, index=[['x', 'x', 'y', 'y'], [1, 2, 1, 2]])
df_multi.index.names = ['group', 'number']
print(df_multi)

              A  B
group number      
x     1       1  5
      2       2  6
y     1       3  7
      2       4  8


In [79]:
#DataFrame Window Functions (rolling, expanding)
df_win = pd.DataFrame({'A': [1, 2, 3, 4]})
print('Rolling sum:', df_win['A'].rolling(window=2).sum())
print('Expanding sum:', df_win['A'].expanding().sum())

Rolling sum: 0    NaN
1    3.0
2    5.0
3    7.0
Name: A, dtype: float64
Expanding sum: 0     1.0
1     3.0
2     6.0
3    10.0
Name: A, dtype: float64


In [80]:
 #DataFrame Categorical Data
df_cat = pd.DataFrame({'Type': ['A', 'B', 'A', 'C']})
df_cat['Type'] = df_cat['Type'].astype('category')
print(df_cat['Type'])

0    A
1    B
2    A
3    C
Name: Type, dtype: category
Categories (3, object): ['A', 'B', 'C']


In [81]:
data = {'Name':['john', 'michael', 'sarah', 'anna'],'Age':[28, 34, 29, 24]}

df = pd.DataFrame(data)
df

,Name,Age
0,john,28
1,michael,34
2,sarah,29
3,anna,24


In [82]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [83]:
df.value_counts

<bound method DataFrame.value_counts of       Name  Age
0     john   28
1  michael   34
2    sarah   29
3     anna   24>